<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\EstadoSearch;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $searchModel = new EstadoSearch();
            $dataProvider = $searchModel->search($this->request->queryParams);
            return $this->render('..\estado\index.php', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    //   public function beforeAction($action)
    //   {
    //     //   if (Yii::$app->user->isGuest) {
    //     //       return $this->redirect(['site/login']);
    //     //   }
    //     //   return parent::beforeAction($action);

    //       $rotaAtual = Yii::$app->requestedRoute;

    //       if(in_array($rotaAtual, $this->rotaPermitida)) {
    //           return parent::beforeAction($action);
    //       }
  
    //       if (parent::beforeAction($action)) {
    //           if (Yii::$app->request->isAjax && !Yii::$app->user->identity->id) {
    //               throw new yii\web\NotFoundHttpException();
    //           }
    //           if (\Yii::$app->user->isGuest || !Yii::$app->user->identity->id) {
    //               return $this->redirect(['login'])->send();
    //           }
    //       }
    //       return parent::beforeAction($action);




    //   }

    // public function beforeAction($action)
    // {
    //     if(!Yii::$app->user->isGuest) {
    //         $this->enableCsrfValidation = false;
    //     }
        
    //     if ($action->id == 'login') {
    //         if($_POST && isset($_POST['LoginForm'])
    //             && isset($_POST['LoginForm']['email'])
    //             && $_POST['LoginForm']['email'] == 'integrator')
    //         {
    //             $this->enableCsrfValidation = false;
    //         }
    //     }

    //     return parent::beforeAction($action); // TODO: Change the autogenerated stub
    // }


}
